

server:
  port: 8082

spring:
  application:
    name: consumer-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5


  main:
    allow-bean-definition-overriding: true




#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    timeout: 6000ms
#    jedis:
#      pool:
#        max-active: 200
#        max-wait: -1ms
#        max-idle: 10
#        min-idle: 0
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8091/eureka
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000



