



server:
  port: 8085

spring:
  application:
    name: provider-shop
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
<<<<<<< HEAD
    password: root
=======
    password: wf123-
>>>>>>> b0186584b24b8f4e6e587c30119e29f8b36eae62
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    timeout: 6000ms
#    jedis:
#      pool:
#        max-active: 200
#        max-wait: -1ms
#        max-idle: 10
#        min-idle: 0

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka









